services:
  bd-mongodb:
    container_name: db-mongodb
    hostname: db-mongodb
    image: mongo:latest
    restart: on-failure
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./data-container/mongo-data:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=admin

  mongo-express:
    container_name: mongo-express
    hostname: mongo-express
    image: mongo-express:latest
    restart: on-failure
    expose:
      - 8081
    ports:
      - 8080:8081
    volumes:
    - ./data-container/mongo-express-data:/data
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@db-mongodb:27017/
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=admin